### ISSUE TITLE
[BUG] Pricing config missing?

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-diving#89]
**Describe the bug**
Checking if this should be missing.

Just testing a PR and noticed on sell that I was getting an error about comparing the price to nil.

Looking at the config it seems to be missing the min/max on the config, not sure if this is ok to be missing or such?
https://github.com/qbcore-framework/qb-diving/blob/7392bebfd38221fe65af7e04e5a9e60d7c1e9350/config.lua#L279

**Comment by nzkfc** [comment]
Hmmm something is not right.

I just downloaded the fresh version without any PR's and re-run it (only set my NPC location), I have myself 20 dendrogyra_coral and got $1 for it?

https://i.imgur.com/9w6e0Eo.jpeg

**Comment by Sharkiiie** [comment]
I'm working on fixing this right now.
I see what the issue is, but I'm not sure of the intended behavior of the modifier.

It seems to encourage selling fewer coral at a time, as it gives a lower price if you have more items.
In my opinion, it should probably be the opposite? Or just be removed entirely. Unsure of the logic for adding this function.

**Comment by nzkfc** [comment]
Yeah should be the more you hand in the more you get, because it's supposed
to be risk/reward as cops get pinged when you take coral by chance, if you
get away you should be rewarded.

On our server, we use seafood (paua, kina, mussels etc) instead of coral so
it's kinda like over fishing limits if you get caught with too many.
